alias fa=fastfetch
alias c=clear
alias n=nano
alias ..='cd ..'
alias uu="sudo apt-get update && sudo apt-get upgrade"
alias aac="sudo apt-get clean && sudo apt-get autoclean && sudo apt-get autoremove"
alias lsd='ls -d */'
alias ebrc='nano ~/.bashrc'
alias bali='nano ~/.bash_aliases'
alias ptero='cd /var/www/pterodactyl'
alias h="history | grep "
alias rebr='source ~/.bashrc'
alias reba='source ~/.bash_aliases'
alias bd='cd "$OLDPWD"'
alias restart='systemctl restart'
alias stop='systemctl stop'
alias start='systemctl start'
alias status='systemctl status'
alias binstall='blueprint -install'
alias b='blueprint'
alias bremove='blueprint -install'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'
alias ss='screen -S'
alias sr='screen -r'
alias eptero='nano /etc/pterodactyl/config.yml'
alias editphp='nano /etc/nginx/sites-available/phpmyadmin.conf'
alias engptero='nano /etc/nginx/sites-available/pterodactyl.conf'
